// Desc: This file contains the foundational style overrides for colors
// ============================================================

// Define Overrides
// ============================================================
const colors = {
    transparent: 'transparent',
    black: '#000',
    white: '#fff',
    light: {
        primary: '#ffffff',
        // primary: '#d9d9d9',
        // primary: '#d8f3dc',
        // primary: '#dde5b6',
        // primary: '#dee2e6',
        // primary: '#cfe1b9',
        // primary: '#d8e3e4',
        pureWhite: '#ffffff',
        text: '#081C15',
        inputText: '#1B4332',
        buttonText: '#fff',
        errorText: '#cf3535',
        inputBackground: '#EFF2EF',
        inputBorder: '#4eab8449',
        inputFocusBorder: '#4eab847c',
        checkoutBg: '#c9e89d',
        historyBg: '#b4d291ac',
        historyColor: '#695d07',
        buttonBgColor: '#081C15',
        buttonBgColorHover: '#087642d5',
        dashboardCardBg: '#F7F9FB',
        priceCardBg: '#F7F9FB',
        priceCardBorder: '#a8b1ae1a',
        greenDark: '#081c15',
        inactiveLine: '#eff2ef',
        bbackground: '#d9d9d9',
        stepper: '#d9d9d9',
        teamImageBg: '#269063',
        successFeedbackColor: '#357461e5',
        borderInactive: '#d9d9d9',
        orange: '#f5a61d',
        greenLight: '#d8f3dc',
        greenMedium: '#1b4332',
        greenFlashy: '#9dffce',
        greenPop: '#33c481',
        whitePure: '#ffffff',
        brown: '#6d4c41',
        greyLight: '#f7f9fb',
        greyIntermediate: '#d9d9d9',
        yellow: '#ffdc5f',
        red: '#cf3535',
        blue: '#4285f4',
        greenMidDark: '#415d43',
        greyDark: '#49454f',
        greenDarkTransparent: 'rgba(27, 67, 50, 0.10)',
        purple: '#9747ff',
        stepperGreen: '#081C15',
        tag: '#33C481',
        constantGreenDark: '#081C15',
        videoCover: '#D6D7D6',
        constantWhitePure: '#FFFFFF',
        cardsMainColor: '081C15',
        cardsWhite: '#ffffff',
    },
    dark: {
        primary: '#1B4332',
        text: '#fff',
        buttonText: '#081c15',
        errorText: '#ff6a36',
        inputText: '#1B4332',
        inputBackground: '#fff',
        inputBorder: '#90eb9dba',
        inputFocusBorder: '#22ee177a',
        checkoutBg: '#d0ffd7',
        historyBg: '#081c15',
        historyColor: '#f5a61d',
        buttonBgColor: '#fff',
        buttonBgColorHover: '#d8f3dc',
        dashboardCardBg: '#132F25',
        priceCardBg: '#132F25',
        priceCardBorder: '#a8b1ae1a',
        greyIntermediate: '#d9d9d9',
        greenFlashy: '#9dffce',
        bbackground: '#a8b1ae1a',
        innerCircleBg: '#a8b1ae5e',
        borderInactive: '#777777d7',
        orange: '#ffc662',
        greenLight: '#d0ffd7',
        greenMedium: '#269063',
        greenDark: '#e8f5f1',
        greenPop: '#33c481',
        whitePure: '#081c15',
        brown: '#e29d86',
        greyLight: 'rgba(180, 180, 180, 0.16)',
        yellow: '#ffe999',
        red: '#f53636',
        blue: '#73a5f8',
        greenMidDark: '#72bc77',
        greyDark: '#f1f0f3',
        greenDarkTransparent: 'rgba(116, 222, 177, 0.10)',
        purple: '#af72ff',
        stepperGreen: '#9DFFCE',
        tag: '#D0FFD7',
        constantGreenDark: '#081C15',
        videoCover: '#24342F',
        constantWhitePure: '#FFFFFF',
        cardsMainColor: 'F4FBF9',
        cardsWhite: '081C15',
    },
};
// ============================================================

// Export Overrides
// ============================================================
export default colors;
// ============================================================